### ISSUE TITLE
Can't play json file

### ISSUE THREAD

**Issue by Adem68** [xvrh/lottie-flutter#10]
Hi, i can't play json file downloaded from Lottiefiles.com.

I tried with Lottie.asset and Lottie.network.

Animation: https://lottiefiles.com/1347-icon-delivery
Json File: https://assets7.lottiefiles.com/datafiles/oTaonrK3qDgUk9h/data.json

Is json file wrong?

**Comment by xvrh** [comment]
Hi,
Thanks for the report.
I confirm that this file renders correctly in lottie-web and lottie-android but is totally wrong with the flutter port.
Lots of other files from lottiefiles.com seems to render correctly though.
I will have a look for this particular sample.

**Comment by Adem68** [comment]
Thank you

**Comment by xvrh** [comment]
I think I found the bug. This is actually a big bug from the java conversion that may have affected every animation. 
Should be much better now :-)
