### ISSUE TITLE
Is this normal behaviour? Gaussian Blur does not apply and moves layer position.

### ISSUE THREAD

**Issue by ayazemre** [xvrh/lottie-flutter#126]
I am trying to create a simple animation as you can see in the video below. I guess problem is gaussian blur. I used both legacy and new one. It is applied through alpha matte of underlying layer. What I am missing?

https://user-images.githubusercontent.com/68122318/105227553-8c1c5b00-5b72-11eb-9457-95660015d9a8.mp4

**Comment by xvrh** [comment]
Can you share the json file so I can have a look?

**Comment by ayazthemre** [comment]
> Can you share the json file so I can have a look?


https://lottiefiles.com/45668-arrow-with-light-passing-through you can download from here.

**Comment by ayazthemre** [comment]
> Can you share the json file so I can have a look?

Any updates?

**Comment by xvrh** [comment]
I had a look at this animation.
There are 2 bugs actually:
- The gaussian blur is not applied. 
Unfortunately this library (like Lottie-android and Lottie-iOS) doesn't support Layer effects.
- The reflection is cropped. #128 will fix that.

**Comment by ayazthemre** [comment]
> I had a look at this animation.
> There are 2 bugs actually:
> 
> * The gaussian blur is not applied.
>   Unfortunately this library (like Lottie-android and Lottie-iOS) doesn't support Layer effects.
> * The reflection is cropped. #128 will fix that.

Would it impact performance much if I had to do image workaround? Like exporting blurred asset and adding it to comp again.

**Comment by xvrh** [comment]
> Like exporting blurred asset and adding it to comp again.

I think it's the best way to fix this animation. And it will have much better performance than the dynamic blur effect.

**Comment by sonukhare23** [comment]
Hey, I am facing a similar issue. I applied layer effects in my animation, but it is not showing in my json file. Can you please tell me how did you fix it?

**Comment by Danilo-Mota** [comment]
same problem here

**Comment by phanbaohuy96** [comment]
still happened on v3.3.1. Any update here?
Sample:
[gradient_ball.json](https://github.com/user-attachments/files/21678472/gradient_ball.json)
Expectation:
![Image](https://github.com/user-attachments/assets/52e95d8b-6986-4d6f-a44b-8d61bde576a8)
