### ISSUE TITLE
Nullsafety version not compiling on web

### ISSUE THREAD

**Issue by HosseinYousefi** [xvrh/lottie-flutter#133]
Hey, I'm trying to use `lottie-0.8.0-nullsafety.3` but it doesn't compile for web. The error I get:

```
Error: The argument type
'ImageProvider<Object>?' can't be assigned to the parameter type 'ImageProvider<Object>' because 'ImageProvider<Object>?' is nullable and
'ImageProvider<Object>' isn't.
 - 'ImageProvider' is from 'package:flutter/src/painting/image_provider.dart'
 ('../../flutter/packages/flutter/lib/src/painting/image_provider.dart').
 - 'Object' is from 'dart:core'.                                        
    return loadImage(composition, lottieImage, imageProvider);
```

In the code since we have `imageProvider ??= io.loadImageForFile(file, lottieImage);` We know that `imageProvider` is not null because `io.loadImageForFile` returns a non-null value. So this can be fixed by just putting a `!` at the end of `imageProvider`.

**Comment by xvrh** [comment]
Thanks for the report.
