### ISSUE TITLE
The RenderLottie class does not implement "computeDryLayout".

### ISSUE THREAD

**Issue by berkbb** [xvrh/lottie-flutter#138]
Hi, I got The RenderLottie class does not implement "computeDryLayout". in Flutter 2.0.1. Widget returns null. 

```

════════ Exception caught by rendering library ═════════════════════════════════
The RenderLottie class does not implement "computeDryLayout".
The relevant error-causing widget was
SliverFillRemaining
lib/history_widget.dart:593
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was
CustomScrollView
lib/history_widget.dart:598
════════════════════════════════════════════════════════════════════════════════
```

The Lottie Player comes as a child to CustomScrollView slivers. It covered with SliverFillRemaining.

**Comment by xvrh** [comment]
Hello, thank for the report,
Can you can provide a full program that reproduces the error?
Thanks.

**Comment by berkbb** [comment]
Hi. A test app is [here ](https://we.tl/t-y8aOF3W8vL)without Sliver. I got cannot load asset error for Lottie now.

**Comment by berkbb** [comment]
Ooops. I forgot adding assets under "uses-material-design: true" in pubspec.yaml in the context of this test project. After I did it, I got the main error. :)
