### ISSUE TITLE
lottie 1.0.1 in flutter 2

### ISSUE THREAD

**Issue by m2faridi** [xvrh/lottie-flutter#142]
Because lottie >=0.8.0-nullsafety.1 depends on logging ^1.0.0 and socket_io_client 2.0.0-beta.3 depends on logging ^0.11.3+2, lottie >=0.8.0-nullsafety.1 is incompatible with socket_io_client 2.0.0-beta.3.
And because no versions of socket_io_client match >2.0.0-beta.3 <3.0.0, lottie >=0.8.0-nullsafety.1 is incompatible with socket_io_client ^2.0.0-beta.3.
So, because myProject depends on both socket_io_client ^2.0.0-beta.3 and lottie ^1.0.1, version solving failed.
pub get failed (1; So, because myProject depends on both socket_io_client ^2.0.0-beta.3 and lottie ^1.0.1, version solving failed.

**Comment by xvrh** [comment]
Look at `dependency_overrides` to temporarily force the `logging` constraints. https://dart.dev/tools/pub/dependencies#dependency-overrides
