### ISSUE TITLE
Lottie file not displaying as expected on Android and iOS

### ISSUE THREAD

**Issue by advancedngwarati** [xvrh/lottie-flutter#145]
Hi there,
This is my lottie 
[lottie.json.zip](https://github.com/xvrh/lottie-flutter/files/6389287/lottie.json.zip)

This is the expected result of the lottie:

https://user-images.githubusercontent.com/45203079/116350605-7c0bbb80-a7f2-11eb-88d9-c69349e8578f.mov

But what is displayed on the device:

https://user-images.githubusercontent.com/45203079/116350758-c12fed80-a7f2-11eb-8707-11c74858aad7.mp4

Any help to get this fixed is appreciated!

**Comment by Nandan-Wewhare** [comment]
@advancedngwarati how did you solve this?

**Comment by advancedngwarati** [comment]
@Nandan-Wewhare we ended up changing the lottie, we haven't solved that issue yet.

**Comment by vantutrieu97** [comment]
I faced same
