### ISSUE TITLE
Animation padding too large

### ISSUE THREAD

**Issue by marciovalim** [xvrh/lottie-flutter#149]
All my lottie animations have a big padding and this is taking to much space of the screen. How to remove this padding?

**Comment by xvrh** [comment]
The best option is probably to try to edit your animation and re-export it.

If it is not an option, you can try with the [`OverflowBox`](https://api.flutter.dev/flutter/widgets/OverflowBox-class.html) widget from flutter.

Something like:

```dart
SizedBox(
   height: 120,
   child: OverflowBox(
    minHeight: 170,
    maxHeight: 170,
    child: Lottie.asset('animation.json'),
  ),
),
```

**Comment by marciovalim** [comment]
Thanks!

**Comment by toanphung** [comment]
Not working for me
<img width="120" alt="Screen Shot 2021-06-15 at 09 00 09" src="https://user-images.githubusercontent.com/5582540/121981576-18e0e300-cdb8-11eb-902b-4a6d7dd8f428.png">

**Comment by dealfonso** [comment]
I created a tool to calculate the bounding box of a Lottie animation and then removed the padding to create an animation that only contains the visible objects.

The trimmer is part of my Lottie player project at https://github.com/dealfonso/simplelottieplayer

If just want to remove the padding, please use the demo application at https://dealfonso.github.io/simplelottieplayer/lottietrimmer.html (the whole process is done in your browser: no need to upload anything to any server).

**Comment by felipecastrosales** [comment]
> ```dart
> SizedBox(
>    height: 120,
>    child: OverflowBox(
>     minHeight: 170,
>     maxHeight: 170,
> ```

not works as expected.

**Comment by shihabkarimba** [comment]
> I created a tool to calculate the bounding box of a Lottie animation and then removed the padding to create an animation that only contains the visible objects.
> 
> The trimmer is part of my Lottie player project at https://github.com/dealfonso/simplelottieplayer
> 
> If just want to remove the padding, please use the demo application at https://dealfonso.github.io/simplelottieplayer/lottietrimmer.html (the whole process is done in your browser: no need to upload anything to any server).

why the web app properly doesn't work properly
the trim is not working
can you pls fix it

**Comment by dealfonso** [comment]
Hi,

what is the problem with the app? I have just tried it and it seems to work as expected.

<img width="920" alt="Captura de pantalla 2023-10-01 a las 14 53 08" src="https://github.com/xvrh/lottie-flutter/assets/10501975/926e4e77-8f01-4021-962d-220406137b46">

**Comment by babirms** [comment]
> The best option is probably to try to edit your animation and re-export it.
> 
> If it is not an option, you can try with the [`OverflowBox`](https://api.flutter.dev/flutter/widgets/OverflowBox-class.html) widget from flutter.
> 
> Something like:
> 
> ```dart
> SizedBox(
>    height: 120,
>    child: OverflowBox(
>     minHeight: 170,
>     maxHeight: 170,
>     child: Lottie.asset('animation.json'),
>   ),
> ),
> ```

This worked for me, thanks!
