### ISSUE TITLE
profile mode 

### ISSUE THREAD

**Issue by ajnaf** [xvrh/lottie-flutter#15]
works fine on debug mode but when i run on profile mode the images change size and change alignment

**Comment by xvrh** [comment]
Hi, thanks for the report !
Could you add some details about the platform (android, ios, desktop?) and your flutter version?
Also can you provide the lottie file that is not playing correctly.

Thanks

**Comment by ajnaf** [comment]
Android im using the beta version

**Comment by xvrh** [comment]
I'll close this issue since I don't have enough information to reproduce the problem. Please reopen a new issue if you still have the problem.
