### ISSUE TITLE
Lottie Animation Fails to Render on Flutter Web

### ISSUE THREAD

**Issue by kchatr** [xvrh/lottie-flutter#158]
I've recently attempted to add Lottie animations on to my application via the `lottie.asset()` file and have done most of my debugging for Flutter Web on the Chrome browser (91.0.4472.124 stable version). 

However, whenever I start the app and navigate to the screen with the animation, all I get is a black square where the animation should've been and the repeated error message:
`Another exception was thrown: PersistedOffset: is in an unexpected state.`

There seems to be an issue with either the web rendering engine or a conflict with the Lottie package and the Flutter Web platform. My Lottie version is 1.1.0, with Flutter 2.4.0 on the dev channel.

Any resolution or advice on solving the issue would be greatly appreciated!

**Comment by xvrh** [comment]
Hi, which web renderer do you use? I think this library only works well with the CanvasKit renderer.
https://flutter.dev/docs/development/tools/web-renderers

**Comment by kchatr** [comment]
@xvrh Using the CanvasKit renderer works perfectly, thank you so much! 

I was using HTML since my network images weren't loading on CanvasKit (blocked by CORS, so an issue with the renderer itself), but looks like I'll stick with CanvasKit from now on!

Just curious, but is there a reason the HTML renderer can't render Lottie animations from JSON?
