### ISSUE TITLE
Change playback speed

### ISSUE THREAD

**Issue by dalton5** [xvrh/lottie-flutter#160]
Hi,

How can I change the speed of the playback of my lottie?

Thanks,

**Comment by MagnusJohansson** [comment]
Set the duration property to a `Duration()` of your choice.
That will set the duration of the animation, and effectively the speed.

E.g.:

```dart
          Lottie.asset(
            'assets/animations/some-anim.json',
            controller: _animationController,
            onLoaded: (composition) {
              _animationController
                ..duration = Duration(milliseconds: 2200)
                ..forward();
            },
          ),

```

**Comment by lukepighetti** [comment]
would be nice to have this feature where we could specify 0.5, 1.0, 2.0 etc
