### ISSUE TITLE
how to show specific frame ?

### ISSUE THREAD

**Issue by 826327700** [xvrh/lottie-flutter#164]
When I pulldown page , I need control lottie show some frame with page scroll distance. 
For example, the pull-down distance from 0-100, and the lottie playing 0%-100% .
emm..., I'm trying make pull-refresh animation.

**Comment by xvrh** [comment]
When you specify an `AnimationController` you can control the `value` property to show a specific frame.

See the `example` folder for some examples
ie. https://github.com/xvrh/lottie-flutter/blob/master/example/lib/examples/animation_full_control.dart

**Comment by 826327700** [comment]
> When you specify an `AnimationController` you can control the `value` property to show a specific frame.
> 
> See the `example` folder for some examples ie. https://github.com/xvrh/lottie-flutter/blob/master/example/lib/examples/animation_full_control.dart

Thanks！it worked . really cool.
