### ISSUE TITLE
Animation is not working properly in first time

### ISSUE THREAD

**Issue by wrteam-priyansh** [xvrh/lottie-flutter#167]
This is my code snippet
Lottie.asset(
                      "assets/animations/splashLogo.json",
                      animate: true,
                      repeat: true),

Animation is not working as expected in first time

**Comment by saigopin** [comment]
facing same problem, any solution?

**Comment by Ashotjlavyan** [comment]
You should animate lottie file when it's loaded.

```
Lottie.asset(
         "assets/animations/splashLogo.json",
          repeat: false,
          animate: false,
          controller: controller,
          onLoaded: (composition) {
              controller
                ..duration = composition.duration
                ..forward();
          },
        )
```
