### ISSUE TITLE
Shadow missing

### ISSUE THREAD

**Issue by appinteractive** [xvrh/lottie-flutter#169]
Is it possible to get shadow on elements? I did not find any working example. BoxShadow does not respect the form.

**Comment by xvrh** [comment]
There is a recent addition on Lottie-Android (https://github.com/airbnb/lottie-android/pull/1860) that we need to port to Flutter.
Would it solve your use-case?

**Comment by appinteractive** [comment]
@xvrh I guess it would :) I need a shadow from Affter Effects on a single moving element. 

Any timeframe on a possible port?
