### ISSUE TITLE
Regression in animation smoothness between 1.0.1 and 1.1.0

### ISSUE THREAD

**Issue by plx-tech** [xvrh/lottie-flutter#172]
In one of our Lottie animations we noticed that after updating to 1.1.0 (and still present in 1.2.0) the smoothness of the animation was worse. We pinpointed the commit and possible line that causes the issue to be: 

https://github.com/xvrh/lottie-flutter/commit/50495f24e23b5ba33816e413f629021b1b899ab5#diff-f0436fa214c3d4891201d51d9e14027bcfbc4e05514b8b11a25f826ec493eafeR305

By changing back from Flutter's `Cubic` curve to this library's `PathInterpolator.cubic`, the problem seems to be resolved. Is there any reason why you decided to move to the other implementation? And is it possible to revert this behavior back in a future release?
Thank you!

**Comment by xvrh** [comment]
Hi @plx-tech,

> Is there any reason why you decided to move to the other implementation

No particular reason that I could remember. Can you open a pull request with the change?

**Comment by xvrh** [comment]
Fix merged in release v1.2.1

**Comment by plx-tech** [comment]
amazing, thanks!
