### ISSUE TITLE
Error: Type 'AssetBundle' not found.

### ISSUE THREAD

**Issue by kEva0v0** [xvrh/lottie-flutter#197]
10:59:42 .flutter/cache/.pub-cache/hosted/dart-pub.byted.org/lottie-1.2.2/lib/src/lottie.dart:48:5: Error: Type 'AssetBundle' not found.
10:59:42     AssetBundle? bundle,
10:59:42     ^^^^^^^^^^^

**Comment by kEva0v0** [comment]
Maybe miss 
import 'package:flutter/services.dart'
in lottie.dart ?

**Comment by kEva0v0** [comment]
i try lottie 1.2.2 on flutter 2.10 and it works fine 
but my personal repo's flutter version is 2.0.6-0.0.pre.260 and it throw 'cannot find declaration'
so current 'dependency_overrides: lottie 1.2.1' works fine

**Comment by namdiemefo** [comment]
im currently having this issue. any fix ?

**Comment by ivoryxiong** [comment]
+1, the same issue.

**Comment by TheGuyDangerous** [comment]
+1 me too
also the 
import 'package:lottie/lottie.dart'; 

part is greyed out along with 

import 'package:flutter/services.dart'

**Comment by hutomosaktikartiko** [comment]
I got same error, I am using flutter 2.0.3

**Comment by BoniWPy** [comment]
me too on 2.2.2
