### ISSUE TITLE
How do you make the animation run only once?

### ISSUE THREAD

**Issue by Teemo100** [xvrh/lottie-flutter#20]
Lottie.asset("assets/anim.zip", repeat: false, animate: true)

This way the animation is never executed once.

          Lottie.asset("assets/anim.zip",
                        controller: instance.controller,
                        onLoaded: (composition) {
                            instance.controller..duration = composition.duration
                                                         ..forward();
                        })

This is also

**Comment by xvrh** [comment]
Hi,
I added 2 examples to run an animation once:
https://github.com/xvrh/lottie-flutter/blob/master/example/lib/examples/animate_no_repeat.dart
https://github.com/xvrh/lottie-flutter/blob/master/example/lib/examples/run_once.dart

It does the same thing that your example so I'm not sure I understand your issue.
Could you provide a full program with what you are seing and what you expect.

Thanks.
