### ISSUE TITLE
Installation failed in VS Code

### ISSUE THREAD

**Issue by sohailmahmud** [xvrh/lottie-flutter#201]
[lottie] flutter pub get
Running "flutter pub get" in lottie...                          
Error on line 33, column 3 of pubspec.yaml: A package may not list itself as a dependency.
   ╷
33 │   lottie: ^1.2.2
   │   ^^^^^^
   ╵
pub get failed (65;    ╵)
exit code 65

![Screenshot 2022-03-06 001103](https://user-images.githubusercontent.com/46453392/156895290-e57447a3-11c7-4832-b5fa-3354aefcd8e0.png)

**Comment by moaabid** [comment]
Hi @sohailmahmud,

Change your project name. As it same as the package name it will throw an error.
