### ISSUE TITLE
Add AssetLottie to Documentation

### ISSUE THREAD

**Issue by fly-qp** [xvrh/lottie-flutter#215]
I created a custom Tween animation for Lottie. In order to do this i had to load it manually and provide a  RawLottie in an AnimationBuilder. It worked fine with normal Lottie.json BUT when using a lottie file which contains images it just wont show up when loading with  LottieComposition.fromByteData.

In order to fix this you need to use AssetLottei('assets/xyz.json').load() Otherwise images wont load since they are loaded differently and fromByteData does NOT.

**Comment by xvrh** [comment]
Hello, thanks for the heads-up.

You are right `await AssetLottie('assets/xyz.json').load()` is better than the current example with `LottieComposition.fromByteData`.

We need to update the documentation in the README
