### ISSUE TITLE
Lottie animation broken in production, works fine in debug mode.

### ISSUE THREAD

**Issue by ffactory-ofcl** [xvrh/lottie-flutter#216]
My lottie animation shown when starting the app (not a native splash screen) works fine in debug mode but is broken in production.

I created a minimal app to reproduce the bug: https://github.com/ffactory-ofcl/lottie_files_splash_anim_tester/tree/banner

Using another lottie.json file, it works fine: https://github.com/ffactory-ofcl/lottie_files_splash_anim_tester/tree/bell

I discovered this bug while working on my app [four in a row](https://github.com/ffactory-ofcl/fourinarow-app). The animation worked before I upgraded my flutter version to 2.10.5 and migrated the android embedding (`flutterEmbedding`) to version 2, as described [here](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects).

This is debug mode (works fine):

https://user-images.githubusercontent.com/33554869/166253463-4a84264e-0f13-4817-b2d1-b72f087127ba.mp4

But in production the animation is broken (positioned at the top, looks scaled, ...):

https://user-images.githubusercontent.com/33554869/166253490-4bd80f53-cee5-4c66-9207-53906897817d.mp4

**Comment by xvrh** [comment]
Hello @ffactory-ofcl,
I've had similar reports in the past and I would like to dig into this.

Can you provide a minimal reproducible example reproducing the problem?

**Comment by xvrh** [comment]
Thanks for the report.
It seems there is a difference in behaviour in Flutter for the property `window.devicePixelRatio` between "debug" and "release".

I'll try to open a bug in the Flutter issue tracker.

In the mean time, you can fix it by adding a small delay at the start of your main method.

**Comment by ffactory-ofcl** [comment]
Thanks for the quick reply, delaying `runApp` by just 20ms seems to fix the issue :) See the above commit (https://github.com/ffactory-ofcl/fourinarow-app/commit/282099fa7ddf9a98f59a3af17a99bf8b5e630325)

One question remains though: how come the bell animation works without delay? The only differences I see is 1) the bell is newer and 2) uses no image resources.

**Comment by xvrh** [comment]
I created https://github.com/flutter/flutter/issues/102963 to report the difference in behaviour between debug & release.
Let's hope it will be fixed that way.

**Comment by ffactory-ofcl** [comment]
Thanks for your effort! It means a lot. If I can help you somehow, let me know.

**Comment by xvrh** [comment]
I think you can use a code like this instead of hardcoding a delay.

```dart
import 'wait_screen_size.dart';

void main() async {
  await waitScreenSizeAvailable();
  runApp(App());
}
```

`wait_screen_size.dart`
```dart
import 'dart:async';
import 'dart:ui';
import 'package:flutter/widgets.dart';

Future<void> waitScreenSizeAvailable() async {
  if (!_hasScreenSize) {
    WidgetsFlutterBinding.ensureInitialized();
    var observer = _Observer();
    WidgetsBinding.instance!.addObserver(observer);
    await observer.hasScreenSize;
    WidgetsBinding.instance!.removeObserver(observer);
  }
}

bool get _hasScreenSize => !window.physicalSize.isEmpty;

class _Observer extends WidgetsBindingObserver {
  final _screenSizeCompleter = Completer<void>();

  Future<void> get hasScreenSize => _screenSizeCompleter.future;

  @override
  void didChangeMetrics() {
    if (!_screenSizeCompleter.isCompleted && _hasScreenSize) {
      _screenSizeCompleter.complete();
    }
  }
}
```

Now, we have to decide wether or not it make sense to have it automatically inside lottie...
