### ISSUE TITLE
Unable to load asset from Lottie.asset().

### ISSUE THREAD

**Issue by Solider1337** [xvrh/lottie-flutter#234]
Loading an asset from a file does not work. I tried with .zip and .json. There are no errors other than that in the application screen.
Everything works fine with Lottie.network, but I need to load the animations from a file. I searched the internet for a long time but found no solution. I tried the old lottie versions but it didn't fix the problem.

![image](https://user-images.githubusercontent.com/53154301/189505844-b8d6f432-def8-4584-95e7-9036d14582ed.png)
![image](https://user-images.githubusercontent.com/53154301/189505840-45d22ab0-e092-4a5e-8687-5e1c3fa78c80.png)
![image](https://user-images.githubusercontent.com/53154301/189505877-16aecb42-cfe8-4fc4-88c4-fbcbaebad785.png)

Lottie version: lottie: ^1.4.2

Flutter doctor:
![image](https://user-images.githubusercontent.com/53154301/189505962-81d65cfc-202e-490c-94e4-1abf52abd1ac.png)

Run:
![image](https://user-images.githubusercontent.com/53154301/189506120-f1b29cc8-1f92-4981-9ff4-c0f7504e5e1f.png)

**Comment by xvrh** [comment]
I think you either have to declare your assets without the "packages" path:

```yaml
  assets:
    - assets/images/118839-sleeping-piggy.zip
```

or use the `package` parameter in the `Lottie.asset` constructor:

```dart
Lottie.asset('assets/images/118839-sleeping-piggy.zip', package: 'pizzaparty')
```

**Comment by Solider1337** [comment]
> 

It did not help.
![image](https://user-images.githubusercontent.com/53154301/189549382-e998a172-ce48-4eec-b09b-38f992b71e1c.png)
![image](https://user-images.githubusercontent.com/53154301/189549387-04f96cf3-1cf5-4acc-8b8c-72080eddd37c.png)


If I use `Lottie.asset('assets/images/118839-sleeping-piggy.zip', package: 'pizzaparty')`
error changes to Bad state: No element

**Comment by Solider1337** [comment]
I checked your solution again, but on .json it works!
![image](https://user-images.githubusercontent.com/53154301/189549756-1477438a-d920-4b25-a775-9da5a9060a9a.png)

`Lottie.asset('assets/images/75816-delivering-pizzas.json', package: 'pizzaparty')`

`assets:
    - packages/pizzaparty/assets/images/75816-delivering-pizzas.json`

**Comment by xvrh** [comment]
Can you send the .zip file to check why it doesn't load?
