### ISSUE TITLE
Hide after animation completes

### ISSUE THREAD

**Issue by CyberGhost007** [xvrh/lottie-flutter#24]
How can I hide lottie after the animation completes?

**Comment by xvrh** [comment]
I added an example that shows how to hide the animation when complete:
https://github.com/xvrh/lottie-flutter/blob/master/example/lib/examples/hide_after_complete.dart

The important part are: 

Add a status listener on the animation controller and update a variable when the animation is completed.
```dart
    _animationController = AnimationController(vsync: this)
      ..addStatusListener((status) {
        if (status == AnimationStatus.completed) {
          setState(() {
            _showAnimation = false;
          });
        }
      });
```

Conditionally display the animation
```dart
if (_showAnimation)
  Lottie.asset(
    'assets/LottieLogo1.json',
     controller: _animationController,
     onLoaded: (composition) {
       animationController
          ..duration = composition.duration
          ..reset()
          ..forward();
        },
  ),
```

**Comment by luiscruzurvenue** [comment]
It works like charm.

**Comment by CyberGhost007** [comment]
Awesome, thanks mate
