### ISSUE TITLE
Unknown point starts with Token.nullToken

### ISSUE THREAD

**Issue by biklas7** [xvrh/lottie-flutter#277]
Using `lottie: 2.3.2` I get this exception when trying to use [this lottie animation](https://app.lottiefiles.com/share/85fd0509-37b6-46cd-8a01-c338c37fb8ba) (it says the link is expired but you can still download as json).

The animation is quite simple, just a bunch of white dots moving around and scaling. So not sure if there's a problem with this package or if there's something in the animation that isn't supported.

**Comment by biklas7** [comment]
So, I just opened the animation on the online Lottie editor and change the size to about half and now it's working.

**Comment by iabhishek-oli** [comment]
I am still facing the issue.using this file [https://app.lottiefiles.com/animation/7099dace-521e-4f56-a882-8cca88fa1cc6?channel=web&source=public-animation&panel=download](url)
