### ISSUE TITLE
On web only Lottie.asset work, not Lottie.network

### ISSUE THREAD

**Issue by Bolling88** [xvrh/lottie-flutter#298]
On the web only Lottie.asset work, not Lottie.network.
It works fine on Android and iOS. 
The only error I get is: [object ProgressEvent].
I have tried several different animations with the same problem. I use canvaskit.

**Comment by xvrh** [comment]
Do you see something in the Chrome Devtools > Network tab? Could it a be CORS issue?

**Comment by Bolling88** [comment]
Yeah was the CORS issue! Sorry, no issue with the lib. 
If others get stuck here as well, see:
https://firebase.google.com/docs/storage/web/download-files#cors_configuration
