### ISSUE TITLE
animation is rendered incorrectly

### ISSUE THREAD

**Issue by nibo** [xvrh/lottie-flutter#31]
We would like to use lottie in our application. However, the animation is rendered incorrectly in the application. Here once the .json, the expected result and the representation in the app.

maybe you have an idea to solve this problem.

Thanks!
[loading_indicator.zip](https://github.com/xvrh/lottie-flutter/files/4402296/loading_indicator.zip)

**Comment by xvrh** [comment]
Hi,
Thanks for the bug report.
I can reproduce the problem. I haven't found the root cause yet but I will definitely give it an other look.

**Comment by xvrh** [comment]
This is fixed in version `v0.3.3`.
Thanks for the report.

**Comment by nibo** [comment]
Thanks for great support! We have already done it and it works as intended.
