### ISSUE TITLE
The gradient in my animation made with Adobe after effects doesn't work as expected.

### ISSUE THREAD

**Issue by ogikun** [xvrh/lottie-flutter#316]
Flutter 3.13.9
lottie_flutter 2.7.0

I am trying to incorporate an animation created with Adobe after effect into an application I am currently working on.

The preview screen on LottieFiles shows the animation as expected, but when I actually display it in the application using this package, the gradient part is not displayed properly.

It is occurring on both android and iOS.

Here are the simplified JSON file and the screenshot of the animation.

[animation_simple.json](https://github.com/xvrh/lottie-flutter/files/13328005/animation_simple.json)

![screenshot](https://github.com/xvrh/lottie-flutter/assets/76401352/871fd043-3873-43e4-af42-7b607f5935df)

**Comment by ogikun** [comment]
This issue was not a gradient bug.
The cause was that the original lottie_android did not support blend mode.
This problem was resolved by reworking the animation without using blend mode.

**Comment by xvrh** [comment]
I think blend mode is coming to Lottie Android: https://github.com/airbnb/lottie-android/pull/2408
Will bring it to Flutter too after

**Comment by fryette** [comment]
@xvrh any news here? Looks like blend mode still not exists

**Comment by xvrh** [comment]
@fryette normally blend modes are supported now: https://github.com/xvrh/lottie-flutter/blob/master/lib/src/model/content/layer_blend.dart#L3

Anything that is not supported in particular that you want to share?
