### ISSUE TITLE
Properties do not get set when using a LottieDelegate

### ISSUE THREAD

**Issue by bpaul7101** [xvrh/lottie-flutter#32]
Hi - thanks for a great library. I was feeling positive when I saw that you added the ability to change properties. However - it seems this is not working or else I am not using the LottieDelegates correctly.

Based on the attached images, can you advise what the correct way is to set the ORANGE fill colour to any other colour ?

This code does not seem to work - what is the format for the const [ ] ? in order to set properties ?

> 
> Lottie.asset(
>             'assets/lottie/Yakuza.json',
>             delegates: LottieDelegates(
>                 text: (initialText) => translate(initialText),
>                 values: [
>                  
>                   ValueDelegate.color(
>                     const ['Layer 1 Outlines', 'Shape', 'Fill'],
>                     value: Colors.red,
>                   ),
>                 ]),

The above code has no effect but if we do : 

> ValueDelegate.color(
>                     const ['**'],
>                     value: Colors.yellow,
>                   ),
> 

Then **ALL** layers will get change which is not the required objective.

Specifying the entire path also doesnt work : 

> 
>  ValueDelegate.color(
>                     const [
>                       'Precomp_Container',
>                       'Layer 1 Outlines_Outer',
>                       'Layer 1 Outlines_Anchor',
>                       'Shapes_Container',
>                       'Container_Outer',
>                       'Shape',
>                       'Fill'
>                     ],
>                     value: Colors.red,
>                   ),

![image](https://user-images.githubusercontent.com/56043190/78061907-d20af700-7385-11ea-80af-9abf9f9bb3ff.png)

![image](https://user-images.githubusercontent.com/56043190/78063093-8b1e0100-7387-11ea-9001-f396bc3f1e38.png)

**Comment by xvrh** [comment]
Hi,
Thanks for the interest in the library.
Can you share with us the lottie file to help to debug?

Normally the "key path" is the same as implemented in Lottie-Android.
Here is the doc:
```java
/**
 * Defines which content to target.
 * The keypath can contain wildcards ('*') with match exactly 1 item.
 * or globstars ('**') which match 0 or more items.
 *
 * For example, if your content were arranged like this:
 * Gabriel (Shape Layer)
 *     Body (Shape Group)
 *         Left Hand (Shape)
 *             Fill (Fill)
 *             Transform (Transform)
 *         ...
 * Brandon (Shape Layer)
 *     Body (Shape Group)
 *         Left Hand (Shape)
 *             Fill (Fill)
 *             Transform (Transform)
 *         ...
 *
 *
 * You could:
 *     Match Gabriel left hand fill:
 *        new KeyPath("Gabriel", "Body", "Left Hand", "Fill");
 *     Match Gabriel and Brandon's left hand fill:
 *        new KeyPath("*", "Body", Left Hand", "Fill");
 *     Match anything with the name Fill:
 *        new KeyPath("**", "Fill");
 *
 *
 * NOTE: Content that are part of merge paths or repeaters cannot currently be resolved with
 * a {@link KeyPath}. This may be fixed in the future.
 */
```

Let me know if you make progress.

**Comment by bpaul7101** [comment]
Hi again, sorry - I completely forgot to attach the sample json file.  Here it is - It would be great to be able to change any layers here , i.e

1) The orange background and
2) The colour of the exclamation

Thank you.


[warningShimmer.json.zip](https://github.com/xvrh/lottie-flutter/files/4411252/warningShimmer.json.zip)

**Comment by xvrh** [comment]
Hi,
I quickly tried your animation. I dropped it in the lottiefiles.com player to find the layer's names: https://edit.lottiefiles.com/?src=https%3A%2F%2Fassets9.lottiefiles.com%2Fpackages%2Flf20_5ZclXb.json

And with this code:
```dart
LottieDelegates(
  values: [
    for (var i in ['1', '2', '5'])
      ValueDelegate.color(['Layer $i Outlines', '**'], value: Colors.red),
    for (var i in ['3', '4'])
      ValueDelegate.color(['Layer $i Outlines', '**'],  value: Colors.greenAccent),
  ],
)
```

I can have this result:
![warningShimmerModified](https://user-images.githubusercontent.com/5110923/78187544-dfe87700-746e-11ea-9b41-9f1be6b13241.png)

**Comment by bpaul7101** [comment]
Thank you xavier - I noticed that you are using a globstar for the property ... If you were to remove this and try and navigate down the Lottie layer and specifically specify the Fill property (Or any property) you will find that nothing gets set - which is the issue I'm having.

**Comment by xvrh** [comment]
You can use a "key path" like this:  `['Layer 1 Outlines', 'Group 1', 'Fill 1']`
I added more tests here: https://github.com/xvrh/lottie-flutter/pull/35/files

**Comment by Toolenaar** [comment]
Hi a designer handed me this animation and I need to color in all layers in the file with the same color. Any idea which path or trick I need to use to do this? 

[animation.json](https://firebasestorage.googleapis.com/v0/b/pebbl-dc758.appspot.com/o/images%2Fstudy_data.json?alt=media&token=b2775679-17ec-4ca5-b917-ac00f2bcc610)

**Comment by alexda12** [comment]
Flare can do this.

[your designer file.txt](https://github.com/xvrh/lottie-flutter/files/5418286/your.designer.file.txt)
![image](https://user-images.githubusercontent.com/58634787/96772480-1b329f00-13db-11eb-8166-8e64e06e0546.png)

**Comment by Toolenaar** [comment]
> Flare can do this.
> 

Ow sorry I  was not clear need to color this dynamically in code

**Comment by Toolenaar** [comment]
> Flare can do this.
> 

Ow sorry I was not clear need to color this dynamically in code
