### ISSUE TITLE
Using this library will use a lot of GPUs, even if `enableRenderCache` has been used

### ISSUE THREAD

**Issue by shuax** [xvrh/lottie-flutter#322]
Loading a very simple animation will use 30% of the GPU, and the edges of the window will constantly refresh and flicker.

![image](https://github.com/xvrh/lottie-flutter/assets/6940583/acea313e-ad7a-486e-9845-d5a47d02b16c)
GPU:Intel(R) UHD Graphics 770

https://github.com/xvrh/lottie-flutter/assets/6940583/1dd8a309-1694-4d43-baac-887b8f45c07a

**Comment by xvrh** [comment]
Can you provide a reproducible example?

**Comment by shuax** [comment]
Even if I use LinearProgressIndicator, it will occupy a lot of GPU, which should not be lottie's problem.
