### ISSUE TITLE
How should I playsegment?

### ISSUE THREAD

**Issue by nroyliu** [xvrh/lottie-flutter#329]
Animation transitions and results in the same Lottie.
How can I implement like Flutter web playSegment method?

**Comment by xvrh** [comment]
You can provide a custom AnimationController and use the `animateTo` method.
Have a look at this example: https://github.com/xvrh/lottie-flutter/blob/master/example/lib/examples/markers.dart

**Comment by nroyliu** [comment]
I have tried this method before, it seems that I did not pass the correct parameters

**Comment by nroyliu** [comment]
> You can provide a custom AnimationController and use the `animateTo` method. Have a look at this example: https://github.com/xvrh/lottie-flutter/blob/master/example/lib/examples/markers.dart

I have tried this method before, it seems that I did not pass the correct parameters
