### ISSUE TITLE
Privacy Manifest file for IOS 

### ISSUE THREAD

**Issue by iamwalter** [xvrh/lottie-flutter#338]
This plugin is listed on https://developer.apple.com/support/third-party-SDK-requirements/ as requiring a privacy manifest. This should be added to avoid apps using this package from not being able to submit to the app store.

Thank you.

**Comment by iamwalter** [comment]
I just realised it seems this plugin doesn't rely on any native iOS components.  Would you mind confirming if that means this step can be skipped? Thanks.

**Comment by xvrh** [comment]
Yeah I think the mention is about the Lottie iOS project: https://github.com/airbnb/lottie-ios

This library is not a plugin, this is just pure dart code that will be inlined with your app's code.
