### ISSUE TITLE
can't load json animation

### ISSUE THREAD

**Issue by devmfouad** [xvrh/lottie-flutter#348]
I designed my animation using [lottiefiles.com](url) and it's work on website as expected and exported as json
but when load this json on my app it not load and gives me expected an int error
please check attached screenshot
Thanks
![Screenshot 2024-05-12 at 1 09 44 PM](https://github.com/xvrh/lottie-flutter/assets/74681871/9ef02972-ef9f-40ec-b4f3-dccb937513c9)

**Comment by xvrh** [comment]
It would help if I can reproduce. Can you share the json file?

**Comment by devmfouad** [comment]
[kona_splash_animation.json](https://github.com/xvrh/lottie-flutter/files/15304479/kona_splash_animation.json)

**Comment by devmfouad** [comment]
did you fix the issue @xvrh if yes how can i fix ?

**Comment by xvrh** [comment]
@devmfouad should be fixed in the latest version (v3.1.2).
