### ISSUE TITLE
How can I let the click or slide event penetrate the lottie animation?   

### ISSUE THREAD

**Issue by Robert-Stackflow** [xvrh/lottie-flutter#356]
When I draw a lottie animation on the screen, such as when I draw a heart animation when double-clicking the screen, I will not be able to click or slide the part of the screen where the lottie animation exists until the animation is completed. How can I let the click or slide event penetrate the lottie animation?

**Comment by xvrh** [comment]
If you want to totally ignore the animation during hit testing, you can wrap your `Lottie` widget with a `IgnorePointer`. See doc: https://api.flutter.dev/flutter/widgets/IgnorePointer-class.html

**Comment by Robert-Stackflow** [comment]
Thank you! Perfect solution!
