### ISSUE TITLE
OFFICIAL LOTTIE JS FILE IS HACKED - DO NOT USE @2.0.6

### ISSUE THREAD

**Issue by andreujuanc** [xvrh/lottie-flutter#381]

**Comment by Baghdady92** [comment]
yes i'm getting crazy pop up messages

**Comment by sabinthomas** [comment]
seeing this on `3.1.2`

**Comment by sabinthomas** [comment]
Saw this thread on x explaining what package was hacked --> https://x.com/blockaid_/status/1851729469142372711
