### ISSUE TITLE
Go to  specific frame like react native version.

### ISSUE THREAD

**Issue by behiunforgiven** [xvrh/lottie-flutter#41]
in react native version we can play animation from one frame to another

```
animation.current.play(start, end);
```

How can we do this in flutter?

**Comment by xvrh** [comment]
This is already possible with a custom animation controller.
You can specify a `lowerBound` and `upperBound` to the `AnimationController` or a `min` and `max` to the `repeat` method.

ie for a repeat between frame 0 to 20% of the animation
```dart
Lottie.asset(
  'assets/LottieLogo1.json',
  controller: _controller,
  onLoaded: (composition) {
    _controller
    ..duration = composition.duration ~/ 5
    ..repeat(min: 0.0, max: 0.2, reverse: true);
  },
)
```

You don't specify a start and stop frame but a ratio of the animation (between 0.0 and 1.0).

Clearly the API could be improved or at least documented :-)
Maybe we can simply add some methods to the `LottieComposition` class to easily compute the ratio and the duration from a frame index.
