### ISSUE TITLE
Feature request - allow to display specific frame

### ISSUE THREAD

**Issue by danidino123** [xvrh/lottie-flutter#47]
We would like to display first or last frame in some cases. would be great to have this ability

**Comment by luiscruzurvenue** [comment]
This would be great.

**Comment by xvrh** [comment]
With a custom `AnimationController` you can control wish frame to show by specifiyng the `controller.value` (between 0.0 and 1.0)
I added this example on how to use an `AnimationController`: https://github.com/xvrh/lottie-flutter/blob/master/example/lib/examples/animation_full_control.dart
