### ISSUE TITLE
Play animation on tap

### ISSUE THREAD

**Issue by luiscruzurvenue** [xvrh/lottie-flutter#48]
Hello, how can we play the animation when the user taps in the UI? :)

Any example?

**Comment by xvrh** [comment]
I added this example to show how to use a custom `AnimationController` to have full control on when to play the animation.
https://github.com/xvrh/lottie-flutter/blob/master/example/lib/examples/animation_full_control.dart

**Comment by luiscruzurvenue** [comment]
Nice, thanks for sharing the example.
