### ISSUE TITLE
Gray container bug after build

### ISSUE THREAD

**Issue by mukireus** [xvrh/lottie-flutter#51]
I have a bug. These gray containers are lottie animation. I see animation in debug mode. I released app but I can't see animation. 
Project : https://github.com/mukireus/flutter_covid_19_tracker

Before Build:
![Screenshot_20200418-230948](https://user-images.githubusercontent.com/33984759/79670212-01b16000-81ca-11ea-931b-3bd0445a929e.png)

After Build : 
![photo_2020-04-18_22-06-45](https://user-images.githubusercontent.com/33984759/79670109-51435c00-81c9-11ea-8f59-52da70c1f4d3.jpg)

**Comment by xvrh** [comment]
Hi, thanks for the report.
I checked-out the example and I can reproduce the difference with debug and release/profile mode.

I don't understand yet what's going on.
When I edit the "semptom_container.dart" file and remove the `Expanded` widget (line 39) the animation works. 
I'm not familiar with the `Table` widget neither. May be you can rewrite that layout with Column and Row to see if it makes a difference?

Anyway, I'll try to investigate further because the difference between debug and release mode is really worrying.

**Comment by xvrh** [comment]
Also I see this error in the console
```
The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a
I/flutter ( 3494): RenderObject, which has been set up to accept ParentData of incompatible type ParentData.
I/flutter ( 3494): Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically,
I/flutter ( 3494): Expanded widgets are placed directly inside Flex widgets.
I/flutter ( 3494): The offending Expanded is currently placed inside a ConstrainedBox widget.
I/flutter ( 3494): The ownership chain for the RenderObject that received the incompatible parent data was:
I/flutter ( 3494):   Padding ← Expanded ← ConstrainedBox ← Container ← TableCell ← Table ← Padding ← DecoratedBox ←
I/flutter ( 3494): ConstrainedBox ← Container ← ⋯
```

So I think there is something wrong with the layout around the lottie animation.

**Comment by mukireus** [comment]
Thank you for the answer. I continue to research. I will try your suggestion.

**Comment by mukireus** [comment]
I fixed this bug. 
I did some research. I found that the rendering problem occurred in the UI. As a result, `Container `rendering in `Table` takes priority and `lottie animation` is left behind. I solved this problem with `Aspect Ratio`.

Before Code : 
 ```
 TableCell(
   child: Container(
      height: MediaQuery.of(context).size.height * .10,
      width: MediaQuery.of(context).size.width * .16,
         child: Expanded(
           child: Padding(padding: const EdgeInsets.only(top: 8.0), 
			child: Center(child: Lottie.network(
				widget.animationPath, 
				fit: BoxFit.fitHeight)))))),
```
After Code : 
```
TableCell(
 child: AspectRatio(
   aspectRatio: 2,
   child: Center(child: Lottie.network(widget.animationPath, fit: BoxFit.fitHeight))))
```
