### ISSUE TITLE
Delayed restart repeat

### ISSUE THREAD

**Issue by ricardogobbo** [xvrh/lottie-flutter#52]
Is it possible to implement a delayed property to specify a Duration to restart the lottie animation?

Something like that:

`Lottie.asset("assets/lottie.json", 
  repeat: true, 
  animate: true, 
  delayedRestart: Duration(seconds: 3), 
)`

**Comment by xvrh** [comment]
The recommendation is to use a custom AnimationController to have full control on how to run the animation.
