### ISSUE TITLE
load from json object

### ISSUE THREAD

**Issue by sultanmyrza** [xvrh/lottie-flutter#53]
I want to preload lottie from remote
and make a slider where on slide user can play other lotties without waiting response from remote.

Loading lotties from asset directory is not an options since I have a lot of lottiefiles

Do you have an example of loading lottie files from JSON object or it is feature request?

Best regards,
Sam

P.S: Most stable lottie lib for flutter so far. Good job!

**Comment by sultanmyrza** [comment]
Could not find exmaple for 
` Lottie.file(file)`
can you please provide one

**Comment by xvrh** [comment]
Hi, thanks for your interest in this library

There is the `LottieComposition.fromBytes` getter that allows to load a lottie composition from a list of bytes (loaded from the network for instance).

```dart
  Future<LottieComposition> _loadComposition() async {
    var response = await get('<url>'); // from the "http" library
    return LottieComposition.fromBytes(response.bodyBytes);
  }
```

And you display the `LottieComposition` with the `Lottie` constructor:

```dart
  @override
  Widget build(BuildContext context) {
    return FutureBuilder<LottieComposition>(
      future: _futureComposition,
      builder: (context, snapshot) {
        if (snapshot.hasError) return ErrorWidget(snapshot.error);
        if (snapshot.data == null) return CircularProgressIndicator();
        return Lottie(composition: snapshot.data);
      },
    );
  }
```

Also there is the `Lottie.memory` constructor that may help you.

The `Lottie.file` is very easy to use. 
There is this [example](https://github.com/xvrh/lottie-flutter/blob/master/example/lib/examples/save_frames.dart) that saves and load lottie animation to files in a "temp" directory.

**Comment by sultanmyrza** [comment]
Thank you. It's working now.

In my app user can choose subject
it opens subject page which loads lottie files from remote(in avarage 10-15 lottie files)
and user can swipe left right to see lottie animations

one problem is 
first animations start from beginning
but when user swipe to next,prev animation it starts not from beginning

there is a way to start from beginning right?

By the way any tips to optimize loading and playing lottie files?

**Comment by xvrh** [comment]
The recommendation is to use a custom AnimationController to have full control on how to run the animation.
