### ISSUE TITLE
Playback using markers

### ISSUE THREAD

**Issue by appycamper** [xvrh/lottie-flutter#59]
Hi, 

Not sure if this library allows this but I'm trying to achieve something written about [here](https://medium.com/swlh/controlling-lottie-animation-with-markers-5e9035d94623) using markers. 

Does this library support this feature? and if not is it on the roadmap? 

Many thanks

**Comment by xvrh** [comment]
Hi,
Thanks for the interest.

It should already be possible to do this. The "[marker](https://github.com/xvrh/lottie-flutter/blob/7e81ec3f69fb0c28c2ea4908b1681723b5546998/lib/src/model/marker.dart#L3)" are parsed and exposed in the `LottieComposition` class (`List<Marker> get markers`).
You can then configure the AnimationController to play between some specific frames ([example](https://github.com/xvrh/lottie-flutter/blob/7e81ec3f69fb0c28c2ea4908b1681723b5546998/example/lib/examples/animation_full_control.dart#L89)

But I agree that a full example would be better. And probably add some utilities functions to make it simpler. 👍 

I'll have a look.

**Comment by appycamper** [comment]
Thanks,

In your [example](https://github.com/xvrh/lottie-flutter/blob/7e81ec3f69fb0c28c2ea4908b1681723b5546998/example/lib/examples/animation_full_control.dart#L89)  are the start and end times percentages of the animation? If so how would you go about specifying starting from actual frames. 

Many thanks,

**Comment by xvrh** [comment]
I added a small example here: https://github.com/xvrh/lottie-flutter/blob/master/example/lib/examples/markers.dart
It is based on the article you provided.

I also had to export the `Marker` class from the library and add `Marker.start` and `Marker.end` to convert from the "frame number" to the "progress" ratio expected by the AnimationController.  (https://github.com/xvrh/lottie-flutter/blob/0715f6a40248403266ddd0074c25acf55fec4b84/lib/src/model/marker.dart#L17)

Those changes are published with `v0.3.6`

**Comment by appycamper** [comment]
Thanks, I'll try it out!
