### ISSUE TITLE
Icon isn't animating correctly

### ISSUE THREAD

**Issue by lukepighetti** [xvrh/lottie-flutter#60]
This `hurricane.json` file is not animating correctly.

https://lottiefiles.com/7708-hurricane

Actual:
![ezgif-3-20d2b8dcd986](https://user-images.githubusercontent.com/666539/82089120-f9611d80-96c0-11ea-9935-aa712b7a0b27.gif)

Expected:
![ezgif-3-bf3e4bd72be8](https://user-images.githubusercontent.com/666539/82089214-35947e00-96c1-11ea-9f81-0e00d1eae8fc.gif)

[hurricane.json.zip](https://github.com/xvrh/lottie-flutter/files/4636776/hurricane.json.zip)

**Comment by xvrh** [comment]
Thanks again for the report.
`v0.3.5` have the fix :-)

**Comment by lukepighetti** [comment]
Confirmed working! Thanks for the quick attention.
