### ISSUE TITLE
web support?

### ISSUE THREAD

**Issue by softmarshmallow** [xvrh/lottie-flutter#62]
is there any plans or existing web support on this project?

**Comment by xvrh** [comment]
This library should already work partially on web.
You have to run it with the "CanvasKit" rendering backend (based on WebGL). With a command like this:
`flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true --profile`.

I don't think the normal rendering backend (html/css) work at this time.

If you have some errors, you can add it here and I will have a look.

**Comment by softmarshmallow** [comment]
@xvrh thanks for the reply, if the web is working on purpose can you add web tag on README?
perhaps web deploy guideline could be helpful to.

or setting `--dart-define=FLUTTER_WEB_USE_SKIA=true --profile` via in code. for production

**Comment by xvrh** [comment]
The web story has evolved a lot since this issue. Please reopen a new bug if you have concrete issue with the web version.
