### ISSUE TITLE
Import error when using with google_maps_flutter package

### ISSUE THREAD

**Issue by Adem68** [xvrh/lottie-flutter#64]
Hi, 

I'm using lottie and google\_maps\_flutter package in my project. When I updated lottie version to 0.3.6 I got this error.

```
Error: 'Marker' is imported from both 'package:google_maps_flutter_platform_interface/src/types/marker.dart' and 'package:lottie/src/model/marker.dart'.
```

Then i downgrade lottie version to 0.3.5.

**Comment by Adem68** [comment]
I solved problem via adding as prefix to lottie when importing.

```
import 'package:lottie/lottie.dart' as lottie;

lottie.Lottie.network(
  'https://raw.githubusercontent.com/xvrh/lottie-flutter/master/example/assets/Tests/WeAccept.json',
  onLoaded: (composition) {
    if (composition.warnings.isNotEmpty) {
      print(composition.warnings.join('\n'));
    }
  },
),
```

**Comment by xvrh** [comment]
Alternatively you can use a `hide` clause:
```dart
import 'package:lottie/lottie.dart' hide Marker;
```

Anyway, maybe I should rename the class to `LottieMarker`

**Comment by Adem68** [comment]
I think renaming class to `LottieMarker` will be cool

**Comment by Adem68** [comment]
I think renaming class to `LottieMarker` will be cool
