### ISSUE TITLE
images referenced from json not loading

### ISSUE THREAD

**Issue by appycamper** [xvrh/lottie-flutter#65]
[example.zip](https://github.com/xvrh/lottie-flutter/files/4658140/example.zip)

I've attached an example of json that references some images in a folder. I've made sure to add both the json and images folder to assets but for some reason the animation does not load the images. 

However if I zip the animation and load the animation as a zip file it works, I'm trying to make it work without the zip file though. 

Is referencing images from json not currently supported?

**Comment by xvrh** [comment]
This is supported and if it doesn't work, this is a bug I need to investigate.

I quickly tried your example and it seems to work for me.
Note that you have to declare the 2 folders in your `pubspec.yaml`

```yaml
flutter:
  assets:
    - assets/example/
    - assets/example/images/
``` 

This is a rule of Flutter: https://flutter.dev/docs/development/ui/assets-and-images#specifying-assets

**Comment by appycamper** [comment]
That's very strange that it works for you. My relevant pubspec:

`assets:
    - assets/animations/
    - assets/animations/example/
    - assets/animations/example/images/
`

Lottie code:

`
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:lottie/lottie.dart';

class SvgTestScreen extends StatefulWidget {
  static const String routeId = 'svg_test_screen';

  @override
  _SvgTestScreenState createState() => _SvgTestScreenState();
}

class _SvgTestScreenState extends State<SvgTestScreen> {
  Future<LottieComposition> _composition;

  @override
  void initState() {
    super.initState();
    _composition = _loadComposition();
  }

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Scaffold(
          body: SafeArea(
            child: FutureBuilder<LottieComposition>(
              future: _composition,
              builder: (_, snapshot) => snapshot.hasData
                  ? Lottie(composition: snapshot.data)
                  : Center(child: CircularProgressIndicator()),
            ),
          ),
        ),
      );

  Future<LottieComposition> _loadComposition() async {
    var assetData =
        await rootBundle.load('assets/animations/svg_test/data.json');
    return LottieComposition.fromByteData(assetData);
  }
}
`

If I try to load example.zip this works fine but as soon as I unzip and try to load the json the animation is blank. Strangely if I try to print snapshot.data, I can see the json is loaded, it's just the animation won't show, almost as if the images can't be found.

Any idea?

**Comment by appycamper** [comment]
I found that using 
```
Lottie.asset('assets/animations/example/data.json')
```
works but 
```
await rootBundle.load('assets/animations/example/data.json');
```
does NOT work. I guess this makes sense since rootBundle.load only loads the json file and not the images. 

Is there any way I can take advantage of the async feature (i.e. showing loading indicator) while still using Lottie.asset()? 

Thanks

**Comment by xvrh** [comment]
> Is there any way I can take advantage of the async feature (i.e. showing loading indicator) while still using Lottie.asset()?

You can load a `LottieComposition` from your assets with the associated images with:
```dart
var composition = await AssetLottie('assets/example.json').load();
```

This class also cache the composition in an internal cache.

If you don't want the cache and want to perform the image loading yourself, you can use something like:
```dart
    var data = await rootBundle.load('assets/example.json');
    var composition = await LottieComposition.fromByteData(data);

    // Loop over the images declared in the composition and load them.
    for (var image in composition.images.values) {
      var imageData = await rootBundle.load('asset/example/images/${image.fileName}');
      
      var codec = await instantiateImageCodec(imageData.buffer.asUint8List());
      var frame = await codec.getNextFrame();

      // Put the loaded image back in the composition so the drawing code will find it
      image.loadedImage = frame.image;
    }
```

**Comment by appycamper** [comment]
Thanks that's really helpful!
