### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by eagerashwani** [xvrh/lottie-flutter#67]
Hello,
I've face some performance issue with lottie.
App structure:
 -Column
      - Text
      - Image
      - Image
      - Lottie.network
      - GridView
When I scroll down lottie widget delay the scoll.
Hope you understand my problem.

**Comment by namchuai** [comment]
I think I'm having the same issue. I'm putting lottie inside a PageView. The swipe between page is sluggish.

**Comment by NicolasCELLA** [comment]
Same issue

**Comment by VipsDevelopment** [comment]
+1
