### ISSUE TITLE
Play once then loop from frame to frame

### ISSUE THREAD

**Issue by zubyf09** [xvrh/lottie-flutter#69]
Is it possible to play animation once and then call the same animation to loop from e.g. frame 25 to frame 300? I've been looking for documentation in the issues and haven't been able to locate anything.

**Comment by olafurorng** [comment]
One way to do it, would be using markers. You can find example for playing animation between markers here: https://github.com/xvrh/lottie-flutter/commit/0715f6a40248403266ddd0074c25acf55fec4b84#diff-cb22864b4c732e7130c858bb2969fb15

**Comment by xvrh** [comment]
The recommendation is to use a custom AnimationController to have full control on how to run the animation. There are several examples in the example folder:
ie: https://github.com/xvrh/lottie-flutter/blob/master/example/lib/examples/animation_full_control.dart
