### ISSUE TITLE
Missing some detail when render lottie file

### ISSUE THREAD

**Issue by RiuHDuo** [xvrh/lottie-flutter#70]
This lib render as follow:
![99CAFEFF-C7C1-4B9C-AA6C-80D5B4FFCB30](https://user-images.githubusercontent.com/830134/83373780-1c4b3b80-a3fc-11ea-803d-955295a982a1.png)
And lottie lib renders as follow
![18143-discord-nearby-animation](https://user-images.githubusercontent.com/830134/83374180-697bdd00-a3fd-11ea-9e8f-76397dab1e03.gif)

There some thing missing when rendering

Here json file
[bluetoothscanning.json.zip](https://github.com/xvrh/lottie-flutter/files/4709281/bluetoothscanning.json.zip)

**Comment by xvrh** [comment]
Hi,
Thanks for the report.

I would like to have a look at this issue but the attached json file doesn't seem to be the correct one.
Could you please re-attach the json for the animation shown above?

**Comment by xvrh** [comment]
Please try the version `v0.4.0` of this library. 
We disabled merge paths by default, it seems to solve a lot of similar wrong renderings.

**Comment by RiuHDuo** [comment]
> Please try the version `v0.4.0` of this library.
> We disabled merge paths by default, it seems to solve a lot of similar wrong renderings.

v0.4.0 fixed this problem.
