### ISSUE TITLE
For some lottie files，can not draw them perfectly

### ISSUE THREAD

**Issue by ksballetba** [xvrh/lottie-flutter#71]
for example：

https://assets1.lottiefiles.com/private_files/lf30_zfYY24.json

https://assets6.lottiefiles.com/datafiles/e8edab32a32a8a9402f9cd63b457993c/Plane.json

**Comment by xvrh** [comment]
Thanks for the report.
It seems merge paths were the cause of this wrong behaviour. 
I published a new version `0.4.0` with merge paths disabled by default (and an option to enable them).
