### ISSUE TITLE
Insert input for Text Delegates

### ISSUE THREAD

**Issue by kkcy** [xvrh/lottie-flutter#83]
Hi, I'm migrating from Lottie Android and I noticed the Flutter version doesn't have the option to insert input for changing texts dynamically.

In Kotlin, this is possible
```
textDelegate.setText("1", "new text 1")
textDelegate.setText("2", "new text 2")
```

However in Flutter, any text we change is automatically applied to all inputs since we're just using a single state to modify
```
LottieDelegates(
    text: (initialText) => newText, // dynamic text
);
```

**Comment by xvrh** [comment]
Does something like that works:

```dart
    LottieDelegates(
      text: (initialText) => const {
        '1': 'new text 2',
        '2': 'new text 2',
      }[initialText] ?? initialText,
    );
```

You can also build the map dynamically.

**Comment by kkcy** [comment]
Yeah this works perfectly. Thanks for the prompt reply!
