### ISSUE TITLE
Only showing the animated part when given specific dimensions

### ISSUE THREAD

**Issue by sundong212** [xvrh/lottie-flutter#87]
Hi!

I am developing a tablet app, and I run into this problem when I set the width and height to around 200.
The animation is a tent with a blue flag above. And only the flag(upper part) is animated, the tent(bottom part) is a static image.

here is the 
[JSON Preview](https://lottiefiles.com/28040-tent-with-blue-flag). 
[tent.zip](https://github.com/xvrh/lottie-flutter/files/4963791/tent.zip)

It looks good on the web preview.

>environment:
>  sdk: ">=2.7.0 <3.0.0"
>lottie: ^0.4.1

I tested on Ipad pro 9.7 inches simulator / Android tablet simulator with (Android 9) / Android real device (Oppo Color 7, android 10). There's the same problem throughout all environments

Here is my implementation.

>return SizedBox(
>     width: width,
>      height: height,
>      child: Lottie.asset(
>        assets,
>        repeat: true,
>        animate: true,
>      ),
>    );

**When I change the width and height to the number that larger or equal than 400, it will show properly, both the animated flag and the tent**

I wonder whether this is the problem of the library or the JSON itself.

Any help would be appreciated.

Thank you very much!

**Comment by xvrh** [comment]
Hi,
Thanks for the report.

This looks like a bug in this library :-(
I had a quick look but was not able to understand the root cause. I'll try again soon.

**Comment by sundong212** [comment]
> Hi,
> Thanks for the report.
> 
> This looks like a bug in this library :-(
> I had a quick look but was not able to understand the root cause. I'll try again soon.

Thanks for the reply! I fixed the problem by removing the maskProperties in the JSON file. It seems like something went wrong handling the mask.

**Comment by xvrh** [comment]
It should be fixed in `v0.5.0`.
Let me know if you see a problem.

**Comment by sundong212** [comment]
It's working perfectly now! Thank you very much!
