### ISSUE TITLE
Hardware Acceleration?

### ISSUE THREAD

**Issue by kkcy** [xvrh/lottie-flutter#92]
Hi there, is there any way we can enable hardware acceleration for Lottie.
Afaik, we have to enable it manually in Android, it's turned off by default.

**Comment by xvrh** [comment]
Hello,
Do you have a link about what "hardware acceleration" means in the context of Flutter?

This library uses the flutter API to draw the lottie animation (it calls the various drawing methods on the Canvas and Paint class).
Internally, Flutter forwards the drawing calls to the Skia engine (https://skia.org/). Skia will use OpenGL on Android to optimise the drawing. 
As far as I know, this is an internal decision of the engine and I'm not aware of a Flutter API to control that.

**Comment by kkcy** [comment]
Hey, yeah I'm not sure myself, but we have to enable it in Android for some of the heavy animations. 
Thought there might be a toggle for Flutter as well.

Anyway thanks for the quick response!
