### ISSUE TITLE
[Feature] Change image at run time, just like Lottie-Android

### ISSUE THREAD

**Issue by rdcoder33** [xvrh/lottie-flutter#94]
Hey! Thanks for this plugin.
I can't find any way to replace image at runtime through this plugin.

On Android it can be done as:

```
// First I converted the png I wanted to see at runtime to a bitmap:

Bitmap bitmapImage = BitmapFactory.decodeResource(getResources(), R.drawable.imageBlah);

// I used the lambda: 

lottieAnimationView.setImageAssetDelegate( lottieImageAsset -> bitmapImage);
```

Did this plugin support this? If not then can I see this feature in the near future?

**Comment by bayukp** [comment]
maybe already answered in here https://github.com/xvrh/lottie-flutter/issues/66

**Comment by rdcoder33** [comment]
> maybe already answered in here #66

Yeah, it does the work, I am closing this issue.
