### ISSUE TITLE
Regression: 0.4.1 to 0.5.1

### ISSUE THREAD

**Issue by wiradikusuma** [xvrh/lottie-flutter#97]
With 0.4.1:

![lottie_original](https://user-images.githubusercontent.com/481995/90281303-8c634c80-de96-11ea-9a69-d48142a678c7.png)

After upgrading to 0.5.1:

![lottie_broken](https://user-images.githubusercontent.com/481995/90281326-938a5a80-de96-11ea-8933-e393810f27d2.png)

Source: [box.zip](https://github.com/xvrh/lottie-flutter/files/5076409/box.zip)

**Comment by xvrh** [comment]
Hi, thanks for the report.

I'm not able to reproduce this regression :-(
I tried version `0.4.1` and `0.5.1`, and I get this animation in both cases.
![_box_0_5](https://user-images.githubusercontent.com/5110923/90315518-887a0d80-df1c-11ea-8980-536501937a1e.png)

Can you provide a full reproduction program? Also what version of Flutter are you using and on which target platform?
