### ISSUE TITLE
Mask isn't displayed in animation

### ISSUE THREAD

**Issue by furaiev** [xvrh/lottie-flutter#99]
Hi, thank you for the cool package,

I've found that one of the animations isn't played correctly. The envelope that should move in the box isn't shown at all.
It seems that the reason that the envelope is a mask.
Could you please check?

https://lottiefiles.com/share/Nlbk40
https://assets5.lottiefiles.com/packages/lf20_Nlbk40.json

**Comment by xvrh** [comment]
Thanks for the report.
I tried this animation with Lottie-Android and I don't see the envelope either unfortunately.

This library is based on the android code-base so if a feature is missing in Android, it is missing in Flutter too.

We could try to understand what missing feature is causing this and see if we could implement it in Flutter:
https://github.com/airbnb/lottie/blob/master/supported-features.md
